# HTTP (Tomcat) port
server:
  port: 1111  
# Configure this Discovery Server
eureka:
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
