# HTTP (Tomcat) port
server:
  host: localhost
  port: 9801
# Configure this Discovery Server
eureka:
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${server.host}:${server.port}/eureka/
